---
title: "Gov 50 Final Project"
author: Katniss Li
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts
I am interested in data related to China's anti-sanctions. On June 1, 2021, China implemented the Anti-Foreign Sanctions Law and began to anti-sanction foreign entities in response to foreign sanctions. But what caused China to respond or not to respond? What is the pattern of China's anti-sanctions enforcement? I will use my own collected data to explain these questions.

## Project Proposal
Does the hierarchical ranking of Chinese government officials influence China's response to U.S. sanctions? This research dives into the multifaceted patterns and tactics defining China's counteractions to U.S. sanctions, with a particular focus on the hierarchical standing of targeted Chinese government officials. The Anti-Foreign Sanctions Law, implemented by China, signals not merely a defensive posture but reveals a strategically computed resistance to U.S. sanctions, enacted through a discerning and selective methodology. This investigation immerses itself into the complexities of these enforcement patterns, aiming to decode the foundational elements that direct the scope and nature of China’s retaliatory actions against U.S. sanctions.

By encapsulating an exhaustive data set, the ensuing analysis integrates all pertinent U.S. sanctions against China and corresponding Chinese anti-sanctions up to February 18, 2022, establishing a foundation for exploration. I collected the data myself. The fundamental hypothesis traverses through the intricacies of political hierarchy, positing that the likelihood of China's counteractions may be inherently tied to the official ranking of the sanctioned government officials. From a methodological standpoint, the analysis pivots around an explanatory variable, critically examining whether China’s retaliatory measures are particularly invoked when sanctions are imposed upon high-ranking government officials.

The variable employs binary coding, with ‘1’ symbolizing government officials and ‘0’ indicating non-central government officials, thus providing an analytical instrument. The outcome variable in focus is the count of individuals who were sanctioned by the United States and subsequently anti-sanctioned by China. If an observed increase in China’s responses coincides with U.S. sanctions imposed on government officials, it would validate the hypothesis. Conversely, should there be no observable correlation between an individual’s position as a government official and China’s response, it would contest the hypothesis. Running a regression on the count of China’s responses, a positive and statistically significant coefficient would lend credence to the hypothesis.